name: kts-auto-proxy

description: :-
  GitHub Action for kotlin scripts replacing public repositories
  specified with @file:Repository annotations with their equivalent proxies.

author: pgreze

inputs:
  input_path:
    description: 'Path to the kotlin script file.'
    required: true
  output_path:
    description: 'Specify the output path. Keep empty to overwrite the input file.'
    required: false
  maven_central_proxy:
    description: 'URL of the maven central proxy. This is always specified in order to overwrite the default one.'
    required: true
  repos_to_proxies:
    description: 'List of repositories with their proxies, separated by " -> " separator.'
    required: false

runs:
  using: node20
  main: dist/index.js
