name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Create a kts file containing dumb repos
        run: |
          cat > script.main.kts <<EOF
          @file:Repository("https://example1.org/maven/")
          @file:Repository("https://custom-maven.example3.org/")
          @file:DependsOn("com.example:example:1.0.0")
          println("Hello, world!")
          EOF

      - name: Replace repositories with proxies
        uses: ./
        env:
          ACTIONS_RUNNER_DEBUG: true
        with:
          input_path: 'script.main.kts'
          output_path: 'proxied-script.main.kts'
          maven_central_proxy: 'https://maven.aliyun.com/repository'
          repos_to_proxies: |
            https://example1.org/maven/ -> https://proxied-repo.example2.com/maven/
            https://custom-maven.example3.org/ -> https://us-east4-maven.pkg.dev/gcp-project/repository-name

      - name: Check the content of the file
        run: |
          diff -u <(cat proxied-script.main.kts) - <<EOF
          @file:Repository("https://proxied-repo.example2.com/maven/")
          @file:Repository("https://us-east4-maven.pkg.dev/gcp-project/repository-name")
          @file:Repository("https://maven.aliyun.com/repository")
          @file:DependsOn("com.example:example:1.0.0")
          println("Hello, world!")
          EOF
